apiVersion: perfd/v1
kind: trialConfig
metadata:
  name: reqRate_linear_1000_10000_debug
  appName: nginx
  appVersion: 1.10.3
  resultBucket: perfd
  logBucket: perfd-log
  autoscale: True
  clusterdown: True
  verbosity: 1
  debug: True
spec:
  instanceGroup:
    - image: 238764668013/perfd-generic
      tenancy: dedicated
      instanceType: c5.xlarge
      numInstance: 5
  metaConfig:
    numRun: 20
  resourceConfig:
    numServerInstance: 1
    numClientInstance: 4
    serverInstanceType: c5.xlarge
    clientInstanceType: c5.xlarge
  appConfig:
    fileSize: 1000
    reqRate: [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000]
    numWorkerProc: 1
    numConn: 50
    duration: 30
    numClientThread: 1
