apiVersion: perfd/v1
kind: trialConfig
metadata:
  name: debug
  appName: memcached
  appVersion: 1.4.33
  resultBucket: perfd
  logBucket: perfd-log
  autoscale: True
  clusterdown: False
  verbosity: 1
  debug: True
spec:
  instanceGroup:
    - image: 238764668013/perfd-generic
      tenancy: dedicated
      instanceType: c5.xlarge
      numInstance: 15
  metaConfig:
    numRun: 1
  resourceConfig:
    numServerInstance: 1
    numClientInstance: 1
    serverInstanceType: c5.xlarge
    clientInstanceType: c5.xlarge
  appConfig:
#    keySize: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    keySize: 1
    valueSize: 200
    serverThread: 4
    clientThread: 1
    runTime: 10
    waitTime: 2
    warmupTime: 2

