apiVersion: perfd/v1
kind: trialConfig
metadata:
  name: instanceType_suite_3
  appName: memcached
  appVersion: 1.4.33
  resultBucket: perfd
  logBucket: perfd-log
  autoscale: True
  clusterdown: True
  verbosity: 1
spec:
  instanceGroup:
    - image: 238764668013/perfd-generic
      tenancy: dedicated
      instanceType: c5.xlarge
      numInstance: 5
    - instanceType: r5.xlarge
      numInstance: 5
    - instanceType: m5.xlarge
      numInstance: 5
    - instanceType: c5.2xlarge
      numInstance: 5
    - instanceType: r5.2xlarge
      numInstance: 5
    - instanceType: m5.2xlarge
      numInstance: 5
    - instanceType: c5.4xlarge
      numInstance: 15
  metaConfig:
    numRun: 20
  resourceConfig:
    numServerInstance: 5
    numClientInstance: 5
    serverInstanceType: [c5.xlarge, r5.xlarge, m5.xlarge, c5.2xlarge, r5.2xlarge, m5.2xlarge]
    clientInstanceType: c5.xlarge
  appConfig:
    keySize: 30
    valueSize: 200
    serverThread: [4, 4, 4, 8, 8, 8]
    clientThread: 16
    runTime: 10
    waitTime: 2
    warmupTime: 2
