apiVersion: perfd/v1
kind: trialConfig
metadata:
  name: valueSize_linear_200_2000_suite_3
  appName: memcached
  appVersion: 1.4.33
  resultBucket: perfd
  logBucket: perfd-log
  autoscale: True
  clusterdown: True
  verbosity: 1
spec:
  instanceGroup:
    - image: 238764668013/perfd-generic
      tenancy: dedicated
      instanceType: c5.xlarge
      numInstance: 15
    - instanceType: c5.4xlarge
      numInstance: 15
  metaConfig:
    numRun: 20
  resourceConfig:
    numServerInstance: 5
    numClientInstance: 5
    serverInstanceType: c5.xlarge
    clientInstanceType: c5.4xlarge
  appConfig:
    keySize: 30
    valueSize: [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]
    serverThread: 4
    clientThread: 16
    runTime: 10
    waitTime: 2
    warmupTime: 2

