apiVersion: perfd/v1
kind: trialConfig
metadata:
  name: instanceType_suite_3
  appName: microservice-go-fasthttp
  appVersion: 0.0.1
  resultBucket: perfd
  logBucket: perfd-log
  autoscale: True
  clusterdown: True
  verbosity: 1
spec:
  instanceGroup:
    - image: 238764668013/perfd-generic
      tenancy: dedicated
      instanceType: c5.xlarge
      numInstance: 10
    - instanceType: r5.xlarge
      numInstance: 4
    - instanceType: m5.xlarge
      numInstance: 4
    - instanceType: c5.2xlarge
      numInstance: 4
    - instanceType: r5.2xlarge
      numInstance: 4
    - instanceType: m5.2xlarge
      numInstance: 4
  metaConfig:
    numRun: 20
  resourceConfig:
    numServerInstance: 2
    numClientInstance: 5
    serverInstanceType: [c5.xlarge, r5.xlarge, m5.xlarge, c5.2xlarge, r5.2xlarge, m5.2xlarge]
    clientInstanceType: c5.xlarge
  appConfig:
    frameworkName: go-fasthttp
    numClientThread: 4
    reqRate: 5000
    numConn: 32
    duration: 30
