apiVersion: perfd/v1
kind: trialConfig
metadata:
#  name: numServer_linear_1_5_client_5_commit
  name: test
  appName: nginx
  appVersion: 1.10.3
  resultBucket: perfd
  logBucket: perfd-log
  autoscale: True
  clusterdown: False
  verbosity: 1
spec:
  instanceGroup:
    - image: 238764668013/perfd-generic
      tenancy: default
      instanceType: c5.xlarge
      numInstance: 2
  metaConfig:
    numRun: 1
  resourceConfig:
    numServerInstance: 1
    numClientInstance: 1
    serverInstanceType: c5.xlarge
    clientInstanceType: c5.xlarge
  appConfig:
    fileSize: 1
    reqRate: 1000
    numWorkerProc: 1
    numConn: 20
    duration: 30
    numClientThread: 4
