apiVersion: perfd/v1
kind: trialConfig
metadata:
  name: numWorkerProc_linear_1_16_evidence
  appName: nginx
  appVersion: 1.10.3
  resultBucket: perfd
  logBucket: perfd-log
  autoscale: True
  clusterdown: True
  verbosity: 1
spec:
  instanceGroup:
    - image: 238764668013/perfd-generic
      tenancy: dedicated
      instanceType: c5.4xlarge
      numInstance: 4
    - instanceType: c5.xlarge
      numInstance: 16
  metaConfig:
    numRun: 10
  resourceConfig:
    numServerInstance: 1
    numClientInstance: 4
    serverInstanceType: c5.4xlarge
    clientInstanceType: c5.xlarge
  appConfig:
    fileSize: 1000
    reqRate: 1000
    numWorkerProc: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
    numConn: 50
    duration: 30
    numClientThread: 1
