apiVersion: perfd/v1
kind: trialConfig
metadata:
  name: instanceType_suite_1_place_enforce
#  name: instanceType_suite_1_lat_log
  appName: memcached
  appVersion: 1.4.33
  resultBucket: perfd
  logBucket: perfd-log
  autoscale: True
  clusterdown: True
  verbosity: 1
spec:
  instanceGroup:
    - image: 238764668013/perfd-generic
#      tenancy: default
      tenancy: dedicated
      instanceType: c5.xlarge
      numInstance: 8
    - instanceType: r5.xlarge
      numInstance: 4
    - instanceType: m5.xlarge
      numInstance: 4
    - instanceType: c5.2xlarge
      numInstance: 4
    - instanceType: r5.2xlarge
      numInstance: 4
    - instanceType: m5.2xlarge
      numInstance: 4
  metaConfig:
    numRun: 20
  resourceConfig:
    numServerInstance: 1
    numClientInstance: 1
    serverInstanceType: [c5.xlarge, r5.xlarge, m5.xlarge, c5.2xlarge, r5.2xlarge, m5.2xlarge]
    clientInstanceType: c5.xlarge
  appConfig:
    keySize: 30
    valueSize: 200  # valueSize: "exponential:1"
    serverThread: [4, 4, 4, 8, 8, 8]
    clientThread: 1
    runTime: 10
    waitTime: 2
    warmupTime: 2
