apiVersion: perfd/v1
kind: trialConfig
metadata:
  name: numServer_linear_1_10_suite_1_relaxed
  appName: memcached
  appVersion: 1.4.33
  resultBucket: perfd
  logBucket: perfd-log
  autoscale: True
  clusterdown: True
  verbosity: 1
spec:
  instanceGroup:
    - image: 238764668013/perfd-generic
      tenancy: default
      instanceType: c5.xlarge
      numInstance: 15
  metaConfig:
    numRun: 20
  resourceConfig:
    numServerInstance: [1, 2, 3, 4, 5]
    numClientInstance: 1
    serverInstanceType: c5.xlarge
    clientInstanceType: c5.xlarge
  appConfig:
    keySize: 30
    valueSize: 200  # valueSize: "exponential:1"
    serverThread: 4
    clientThread: 1
    runTime: 10
    waitTime: 2
    warmupTime: 2
