apiVersion: perfd/v1
kind: trialConfig
metadata:
  name: pagerank_input_scale_vary_all
  appName: spark_graph
  appVersion: 2.4.3
  resultBucket: perfd
  logBucket: perfd-spark-graph-vary-all
  autoscale: True
  clusterdown: False
  verbosity: 1
  randomConfigSampling: 100
spec:
  instanceGroup:
    - image: 238764668013/perfd-generic
      tenancy: default
      instanceType: c5.xlarge
      numInstance: 10
    - instanceType: r5.xlarge
      numInstance: 10
    - instanceType: m5.xlarge
      numInstance: 10
    - instanceType: c5.2xlarge
      numInstance: 10
    - instanceType: r5.2xlarge
      numInstance: 10
    - instanceType: m5.2xlarge
      numInstance: 10
  metaConfig:
    numRun: 10
  resourceConfig:
    numServerInstance: [2, 3, 4, 5, 6, 7, 8, 9, 10]
    numClientInstance: 0
    serverInstanceType: [c5.xlarge, r5.xlarge, m5.xlarge, c5.2xlarge, r5.2xlarge, m5.2xlarge]
    clientInstanceType: c5.xlarge
  appConfig:
    appName: sparkpagerank
    numExecutor: -1
    numPartition: 64
    driverAdaptiveGC: True
    inputScale: [1, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]
    randomSeed: random
