apiVersion: perfd/v1
kind: trialConfig
metadata:
  name: version_test_random_order_2
  appName: memcached
  appVersion: 1.4.33
  resultBucket: perfd-ev
  logBucket: perfd-ev-log
  autoscale: True
  clusterdown: True
  verbosity: 1
spec:
  instanceGroup:
    - image: 238764668013/perfd-generic
      tenancy: dedicated
      # TODO: may need to use c5.9xlarge
      instanceType: c5.xlarge
      numInstance: 20
  metaConfig:
    tag: ['1.6.0-alpine', '1.5.21', '1.6.6', '1.5.2-alpine', '1.5.11', '1.5.4', '1.5.16-alpine', '1.5.17', '1.5.14', '1.4.36-alpine', '1.5.15-alpine', '1.5.0-alpine', '1.5', '1.6.2-alpine', '1.5.11-alpine', '1.6.3-alpine', '1.5.9', '1.4.39', '1.5.3-alpine', '1.6.1-alpine', '1.5.2', '1.5.9-alpine', '1.5.8-alpine', '1.5.1-alpine', '1.6.2', '1.6.1', '1.5.12-alpine', '1.5.17-alpine', '1.5.7-alpine', '1.5.20-alpine', '1.5.4-alpine', '1.5.21-alpine', '1.6.5', '1.5.0', '1.5.16', '1.5.6-alpine', '1.5.1', '1.4.33-alpine', '1.6-alpine', '1.4.37-alpine', '1.5.6', '1.4.34', 'alpine', '1.5.15', '1.5.10', '1.6.5-alpine', '1.6.3', '1.5.12', '1.5.20', '1.4.35-alpine', '1.5.5-alpine', '1.5.14-alpine', '1.4.33', '1.6.0', '1.5-alpine', '1.5.3', '1.6', '1.5.19-alpine', '1.5.10-alpine', '1.4.37', '1.4.38', '1.4.34-alpine', '1.5.8', '1.5.22-alpine', '1.5.22', '1.5.5', '1.4.35', '1.4.39-alpine', '1.6.6-alpine', '1.5.7', '1.4.38-alpine', '1.5.19', '1.4.36']
    runner: docker
    numRun: 10
  resourceConfig:
    numServerInstance: 1
    numClientInstance: 1
    serverInstanceType: c5.xlarge
    clientInstanceType: c5.xlarge
  appConfig:
    keySize: [10]
    valueSize: 200
    serverThread: 4
    clientThread: 1
    runTime: 10
    waitTime: 2
    warmupTime: 2

