apiVersion: perfd/v1
kind: trialConfig
metadata:
  name: suite_1_vary_all_no_fieldperpoint_more_100
  appName: influxdb
  appVersion: 1.7.10
  resultBucket: perfd
  logBucket: perfd-log
  autoscale: True
  clusterdown: True
  verbosity: 1
  randomConfigSampling: 100
spec:
  instanceGroup:
    - image: 238764668013/perfd-generic
      tenancy: default
      instanceType: c5.xlarge
      numInstance: 14
    - instanceType: r5.xlarge
      numInstance: 10
    - instanceType: m5.xlarge
      numInstance: 10
    - instanceType: c5.2xlarge
      numInstance: 10
    - instanceType: r5.2xlarge
      numInstance: 10
    - instanceType: m5.2xlarge
      numInstance: 10
  metaConfig:
    numRun: 10
  resourceConfig:
    numServerInstance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    numClientInstance: 4
    serverInstanceType: [c5.xlarge, r5.xlarge, m5.xlarge, c5.2xlarge, r5.2xlarge, m5.2xlarge]
    clientInstanceType: c5.xlarge
  appConfig:
    batchSize: 5000
    numReq: 10
    numPointPerSeries: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]
    fieldPerPoint: 1
    clientConcurrency: 1
    duration: 10
    shardDuration: 7d
    numMeasurement: 1
    tagCard: "10,10,10"
    writeConsistency: "any"
