apiVersion: perfd/v1
kind: trialConfig
metadata:
  name: numServer_suite_3
  appName: microservice-go-fasthttp
  appVersion: 0.0.1
  resultBucket: perfd
  logBucket: perfd-log
  autoscale: True
  clusterdown: True
  verbosity: 1
spec:
  instanceGroup:
    - image: 238764668013/perfd-generic
      tenancy: dedicated
      instanceType: c5.xlarge
      numInstance: 15
  metaConfig:
    numRun: 20
  resourceConfig:
    numServerInstance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    numClientInstance: 5
    serverInstanceType: c5.xlarge
    clientInstanceType: c5.xlarge
  appConfig:
    frameworkName: go-fasthttp
    numClientThread: 4
    reqRate: 5000
    numConn: 32
    duration: 30
