apiVersion: perfd/v1
kind: trialConfig
metadata:
  name: suite_1_vary_all_w_digest
  appName: memcached
  appVersion: 1.4.33
  resultBucket: perfd
  logBucket: perfd-log
  autoscale: True
  clusterdown: True
  verbosity: 1
  randomConfigSampling: 20
spec:
  instanceGroup:
    - image: 238764668013/perfd-generic
      tenancy: default
      instanceType: c5.xlarge
      numInstance: 12
    - instanceType: r5.xlarge
      numInstance: 6
    - instanceType: m5.xlarge
      numInstance: 6
    - instanceType: c5.2xlarge
      numInstance: 6
    - instanceType: r5.2xlarge
      numInstance: 6
    - instanceType: m5.2xlarge
      numInstance: 6
  metaConfig:
    numRun: 10
  resourceConfig:
    numServerInstance: [1, 2, 3, 4, 5]
    numClientInstance: 1
    serverInstanceType: [c5.xlarge, r5.xlarge, m5.xlarge, c5.2xlarge, r5.2xlarge, m5.2xlarge]
    clientInstanceType: c5.xlarge
  appConfig:
    keySize: "exponential:1"
    valueSize: [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]
    serverThread: -1
    clientThread: 1
    runTime: 10
    waitTime: 2
    warmupTime: 2
