metadata:
  creationTimestamp: '2019-06-05 04:03:59.941522'
instanceTypes:
  m5.2xlarge:
    API_Name: m5.2xlarge
    Memory: 32.0
    Compute_Units_(ECU): 31
    vCPUs: 8
    GPUs: 0
    FPGAs: 0
    ECU_per_vCPU: 3.875
    Physical_Processor: Intel
    Clock_Speed(GHz): 2.5
    Intel_AVX: 1
    Intel_AVX2: 1
    Intel_Turbo: 1
    Instance_Storage: EBS
    Instance_Storage:_already_warmed-up: 0
    Instance_Storage:_SSD_TRIM_Support: 0
    Arch: 64-bit
    Network_Performance: Up
    EBS_Optimized:_Max_Bandwidth: 3500.0
    EBS_Optimized:_Throughput: 437.5
    EBS_Optimized:_Max_16K_IOPS: 18750.0
    EBS_Exposed_as_NVMe: 0
    Max_IPs: 60
    Max_ENIs: 4
    Enhanced_Networking: 1
    VPC_Only: 1
    IPv6_Support: 1
    Placement_Group_Support: 0
    Linux_Virtualization: HVM
    On_EMR: 1
    Linux_On_Demand_cost: 0.000124
    Linux_Reserved_cost: 9.3e-05
    RHEL_On_Demand_cost: 0.514
    RHEL_Reserved_cost: 0.375
    SLES_On_Demand_cost: 0.484
    SLES_Reserved_cost: 0.278
    Windows_On_Demand_cost: 0.000227
    Windows_Reserved_cost: 0.000196
    Windows_SQL_Web_On_Demand_cost: 0.887
    Windows_SQL_Web_Reserved_cost: 0.749
    Windows_SQL_Std_On_Demand_cost: 1.712
    Windows_SQL_Std_Reserved_cost: 1.573
    Windows_SQL_Ent_On_Demand_cost: 3.752
    Windows_SQL_Ent_Reserved_cost: 3.613
    Linux_SQL_Web_On_Demand_cost: 0.519
    Linux_SQL_Web_Reserved_cost: 0.381
    Linux_SQL_Std_On_Demand_cost: 1.344
    Linux_SQL_Std_Reserved_cost: 1.205
    Linux_SQL_Ent_On_Demand_cost: 3.384
    Linux_SQL_Ent_Reserved_cost: 3.245
    EBS_Optimized_surcharge: 0
    EMR_cost: 0.096
    Name: M5
  m5.4xlarge:
    API_Name: m5.4xlarge
    Memory: 64.0
    Compute_Units_(ECU): 60
    vCPUs: 16
    GPUs: 0
    FPGAs: 0
    ECU_per_vCPU: 3.75
    Physical_Processor: Intel
    Clock_Speed(GHz): 2.5
    Intel_AVX: 1
    Intel_AVX2: 1
    Intel_Turbo: 1
    Instance_Storage: EBS
    Instance_Storage:_already_warmed-up: 0
    Instance_Storage:_SSD_TRIM_Support: 0
    Arch: 64-bit
    Network_Performance: Up
    EBS_Optimized:_Max_Bandwidth: 3500.0
    EBS_Optimized:_Throughput: 437.5
    EBS_Optimized:_Max_16K_IOPS: 18750.0
    EBS_Exposed_as_NVMe: 0
    Max_IPs: 240
    Max_ENIs: 8
    Enhanced_Networking: 1
    VPC_Only: 1
    IPv6_Support: 1
    Placement_Group_Support: 0
    Linux_Virtualization: HVM
    On_EMR: 1
    Linux_On_Demand_cost: 0.000249
    Linux_Reserved_cost: 0.000187
    RHEL_On_Demand_cost: 0.898
    RHEL_Reserved_cost: 0.621
    SLES_On_Demand_cost: 0.868
    SLES_Reserved_cost: 0.524
    Windows_On_Demand_cost: 0.000453
    Windows_Reserved_cost: 0.000391
    Windows_SQL_Web_On_Demand_cost: 1.774
    Windows_SQL_Web_Reserved_cost: 1.497
    Windows_SQL_Std_On_Demand_cost: 3.424
    Windows_SQL_Std_Reserved_cost: 3.147
    Windows_SQL_Ent_On_Demand_cost: 7.504
    Windows_SQL_Ent_Reserved_cost: 7.227
    Linux_SQL_Web_On_Demand_cost: 1.038
    Linux_SQL_Web_Reserved_cost: 0.761
    Linux_SQL_Std_On_Demand_cost: 2.688
    Linux_SQL_Std_Reserved_cost: 2.411
    Linux_SQL_Ent_On_Demand_cost: 6.768
    Linux_SQL_Ent_Reserved_cost: 6.491
    EBS_Optimized_surcharge: 0
    EMR_cost: 0.192
    Name: M5
  m5.large:
    API_Name: m5.large
    Memory: 8.0
    Compute_Units_(ECU): 8
    vCPUs: 2
    GPUs: 0
    FPGAs: 0
    ECU_per_vCPU: 4
    Physical_Processor: Intel
    Clock_Speed(GHz): 2.5
    Intel_AVX: 1
    Intel_AVX2: 1
    Intel_Turbo: 1
    Instance_Storage: EBS
    Instance_Storage:_already_warmed-up: 0
    Instance_Storage:_SSD_TRIM_Support: 0
    Arch: 64-bit
    Network_Performance: Up
    EBS_Optimized:_Max_Bandwidth: 3500.0
    EBS_Optimized:_Throughput: 437.5
    EBS_Optimized:_Max_16K_IOPS: 18750.0
    EBS_Exposed_as_NVMe: 0
    Max_IPs: 30
    Max_ENIs: 3
    Enhanced_Networking: 1
    VPC_Only: 1
    IPv6_Support: 1
    Placement_Group_Support: 0
    Linux_Virtualization: HVM
    On_EMR: 0
    Linux_On_Demand_cost: 3.1e-05
    Linux_Reserved_cost: 2.3e-05
    RHEL_On_Demand_cost: 0.156
    RHEL_Reserved_cost: 0.121
    SLES_On_Demand_cost: 0.196
    SLES_Reserved_cost: 0.094
    Windows_On_Demand_cost: 5.7e-05
    Windows_Reserved_cost: 4.9e-05
    Windows_SQL_Web_On_Demand_cost: 0.256
    Windows_SQL_Web_Reserved_cost: 0.221
    Windows_SQL_Std_On_Demand_cost: 0.668
    Windows_SQL_Std_Reserved_cost: 0.633
    Windows_SQL_Ent_On_Demand_cost: 0
    Windows_SQL_Ent_Reserved_cost: 0
    Linux_SQL_Web_On_Demand_cost: 0.164
    Linux_SQL_Web_Reserved_cost: 0.129
    Linux_SQL_Std_On_Demand_cost: 0.576
    Linux_SQL_Std_Reserved_cost: 0.541
    Linux_SQL_Ent_On_Demand_cost: 0
    Linux_SQL_Ent_Reserved_cost: 0
    EBS_Optimized_surcharge: 0
    EMR_cost: 0
    Name: M5
  m5.xlarge:
    API_Name: m5.xlarge
    Memory: 16.0
    Compute_Units_(ECU): 16
    vCPUs: 4
    GPUs: 0
    FPGAs: 0
    ECU_per_vCPU: 4
    Physical_Processor: Intel
    Clock_Speed(GHz): 2.5
    Intel_AVX: 1
    Intel_AVX2: 1
    Intel_Turbo: 1
    Instance_Storage: EBS
    Instance_Storage:_already_warmed-up: 0
    Instance_Storage:_SSD_TRIM_Support: 0
    Arch: 64-bit
    Network_Performance: Up
    EBS_Optimized:_Max_Bandwidth: 3500.0
    EBS_Optimized:_Throughput: 437.5
    EBS_Optimized:_Max_16K_IOPS: 18750.0
    EBS_Exposed_as_NVMe: 0
    Max_IPs: 60
    Max_ENIs: 4
    Enhanced_Networking: 1
    VPC_Only: 1
    IPv6_Support: 1
    Placement_Group_Support: 0
    Linux_Virtualization: HVM
    On_EMR: 1
    Linux_On_Demand_cost: 6.2e-05
    Linux_Reserved_cost: 4.7e-05
    RHEL_On_Demand_cost: 0.252
    RHEL_Reserved_cost: 0.183
    SLES_On_Demand_cost: 0.292
    SLES_Reserved_cost: 0.156
    Windows_On_Demand_cost: 0.000113
    Windows_Reserved_cost: 9.8e-05
    Windows_SQL_Web_On_Demand_cost: 0.444
    Windows_SQL_Web_Reserved_cost: 0.374
    Windows_SQL_Std_On_Demand_cost: 0.856
    Windows_SQL_Std_Reserved_cost: 0.787
    Windows_SQL_Ent_On_Demand_cost: 1.876
    Windows_SQL_Ent_Reserved_cost: 1.807
    Linux_SQL_Web_On_Demand_cost: 0.26
    Linux_SQL_Web_Reserved_cost: 0.19
    Linux_SQL_Std_On_Demand_cost: 0.672
    Linux_SQL_Std_Reserved_cost: 0.603
    Linux_SQL_Ent_On_Demand_cost: 1.692
    Linux_SQL_Ent_Reserved_cost: 1.623
    EBS_Optimized_surcharge: 0
    EMR_cost: 0.048
    Name: M5
  m5d.2xlarge:
    API_Name: m5d.2xlarge
    Memory: 32.0
    Compute_Units_(ECU): 31
    vCPUs: 8
    GPUs: 0
    FPGAs: 0
    ECU_per_vCPU: 3.875
    Physical_Processor: Intel
    Clock_Speed(GHz): 2.5
    Intel_AVX: 1
    Intel_AVX2: 1
    Intel_Turbo: 1
    Instance_Storage: 300
    Instance_Storage:_already_warmed-up: 1
    Instance_Storage:_SSD_TRIM_Support: 1
    Arch: 64-bit
    Network_Performance: Up
    EBS_Optimized:_Max_Bandwidth: 3500.0
    EBS_Optimized:_Throughput: 437.5
    EBS_Optimized:_Max_16K_IOPS: 18750.0
    EBS_Exposed_as_NVMe: 0
    Max_IPs: 60
    Max_ENIs: 4
    Enhanced_Networking: 1
    VPC_Only: 1
    IPv6_Support: 1
    Placement_Group_Support: 0
    Linux_Virtualization: HVM
    On_EMR: 1
    Linux_On_Demand_cost: 0.000148
    Linux_Reserved_cost: 0.00011
    RHEL_On_Demand_cost: 0.582
    RHEL_Reserved_cost: 0.418
    SLES_On_Demand_cost: 0.552
    SLES_Reserved_cost: 0.321
    Windows_On_Demand_cost: 0.00025
    Windows_Reserved_cost: 0.000212
    Windows_SQL_Web_On_Demand_cost: 0.955
    Windows_SQL_Web_Reserved_cost: 0.791
    Windows_SQL_Std_On_Demand_cost: 1.78
    Windows_SQL_Std_Reserved_cost: 1.616
    Windows_SQL_Ent_On_Demand_cost: 3.82
    Windows_SQL_Ent_Reserved_cost: 3.656
    Linux_SQL_Web_On_Demand_cost: 0.587
    Linux_SQL_Web_Reserved_cost: 0.423
    Linux_SQL_Std_On_Demand_cost: 1.412
    Linux_SQL_Std_Reserved_cost: 1.248
    Linux_SQL_Ent_On_Demand_cost: 3.452
    Linux_SQL_Ent_Reserved_cost: 3.288
    EBS_Optimized_surcharge: 0
    EMR_cost: 0.113
    Name: M5
  m5d.4xlarge:
    API_Name: m5d.4xlarge
    Memory: 64.0
    Compute_Units_(ECU): 60
    vCPUs: 16
    GPUs: 0
    FPGAs: 0
    ECU_per_vCPU: 3.75
    Physical_Processor: Intel
    Clock_Speed(GHz): 2.5
    Intel_AVX: 1
    Intel_AVX2: 1
    Intel_Turbo: 1
    Instance_Storage: 600
    Instance_Storage:_already_warmed-up: 1
    Instance_Storage:_SSD_TRIM_Support: 1
    Arch: 64-bit
    Network_Performance: Up
    EBS_Optimized:_Max_Bandwidth: 3500.0
    EBS_Optimized:_Throughput: 437.5
    EBS_Optimized:_Max_16K_IOPS: 18750.0
    EBS_Exposed_as_NVMe: 0
    Max_IPs: 240
    Max_ENIs: 8
    Enhanced_Networking: 1
    VPC_Only: 1
    IPv6_Support: 1
    Placement_Group_Support: 0
    Linux_Virtualization: HVM
    On_EMR: 1
    Linux_On_Demand_cost: 0.000296
    Linux_Reserved_cost: 0.000219
    RHEL_On_Demand_cost: 1.034
    RHEL_Reserved_cost: 0.706
    SLES_On_Demand_cost: 1.004
    SLES_Reserved_cost: 0.609
    Windows_On_Demand_cost: 0.0005
    Windows_Reserved_cost: 0.000424
    Windows_SQL_Web_On_Demand_cost: 1.91
    Windows_SQL_Web_Reserved_cost: 1.582
    Windows_SQL_Std_On_Demand_cost: 3.56
    Windows_SQL_Std_Reserved_cost: 3.232
    Windows_SQL_Ent_On_Demand_cost: 7.64
    Windows_SQL_Ent_Reserved_cost: 7.312
    Linux_SQL_Web_On_Demand_cost: 1.174
    Linux_SQL_Web_Reserved_cost: 0.846
    Linux_SQL_Std_On_Demand_cost: 2.824
    Linux_SQL_Std_Reserved_cost: 2.496
    Linux_SQL_Ent_On_Demand_cost: 6.904
    Linux_SQL_Ent_Reserved_cost: 6.576
    EBS_Optimized_surcharge: 0
    EMR_cost: 0.226
    Name: M5
  m5d.large:
    API_Name: m5d.large
    Memory: 8.0
    Compute_Units_(ECU): 8
    vCPUs: 2
    GPUs: 0
    FPGAs: 0
    ECU_per_vCPU: 4
    Physical_Processor: Intel
    Clock_Speed(GHz): 2.5
    Intel_AVX: 1
    Intel_AVX2: 1
    Intel_Turbo: 1
    Instance_Storage: 75
    Instance_Storage:_already_warmed-up: 1
    Instance_Storage:_SSD_TRIM_Support: 1
    Arch: 64-bit
    Network_Performance: Up
    EBS_Optimized:_Max_Bandwidth: 3500.0
    EBS_Optimized:_Throughput: 437.5
    EBS_Optimized:_Max_16K_IOPS: 18750.0
    EBS_Exposed_as_NVMe: 0
    Max_IPs: 30
    Max_ENIs: 3
    Enhanced_Networking: 1
    VPC_Only: 1
    IPv6_Support: 1
    Placement_Group_Support: 0
    Linux_Virtualization: HVM
    On_EMR: 0
    Linux_On_Demand_cost: 3.7e-05
    Linux_Reserved_cost: 2.8e-05
    RHEL_On_Demand_cost: 0.173
    RHEL_Reserved_cost: 0.132
    SLES_On_Demand_cost: 0.213
    SLES_Reserved_cost: 0.105
    Windows_On_Demand_cost: 6.3e-05
    Windows_Reserved_cost: 5.3e-05
    Windows_SQL_Web_On_Demand_cost: 0.273
    Windows_SQL_Web_Reserved_cost: 0.232
    Windows_SQL_Std_On_Demand_cost: 0.685
    Windows_SQL_Std_Reserved_cost: 0.644
    Windows_SQL_Ent_On_Demand_cost: 0
    Windows_SQL_Ent_Reserved_cost: 0
    Linux_SQL_Web_On_Demand_cost: 0.181
    Linux_SQL_Web_Reserved_cost: 0.14
    Linux_SQL_Std_On_Demand_cost: 0.593
    Linux_SQL_Std_Reserved_cost: 0.552
    Linux_SQL_Ent_On_Demand_cost: 0
    Linux_SQL_Ent_Reserved_cost: 0
    EBS_Optimized_surcharge: 0
    EMR_cost: 0
    Name: M5
  m5d.xlarge:
    API_Name: m5d.xlarge
    Memory: 16.0
    Compute_Units_(ECU): 16
    vCPUs: 4
    GPUs: 0
    FPGAs: 0
    ECU_per_vCPU: 4
    Physical_Processor: Intel
    Clock_Speed(GHz): 2.5
    Intel_AVX: 1
    Intel_AVX2: 1
    Intel_Turbo: 1
    Instance_Storage: 150
    Instance_Storage:_already_warmed-up: 1
    Instance_Storage:_SSD_TRIM_Support: 1
    Arch: 64-bit
    Network_Performance: Up
    EBS_Optimized:_Max_Bandwidth: 3500.0
    EBS_Optimized:_Throughput: 437.5
    EBS_Optimized:_Max_16K_IOPS: 18750.0
    EBS_Exposed_as_NVMe: 0
    Max_IPs: 60
    Max_ENIs: 4
    Enhanced_Networking: 1
    VPC_Only: 1
    IPv6_Support: 1
    Placement_Group_Support: 0
    Linux_Virtualization: HVM
    On_EMR: 1
    Linux_On_Demand_cost: 7.4e-05
    Linux_Reserved_cost: 5.5e-05
    RHEL_On_Demand_cost: 0.286
    RHEL_Reserved_cost: 0.204
    SLES_On_Demand_cost: 0.326
    SLES_Reserved_cost: 0.177
    Windows_On_Demand_cost: 0.000125
    Windows_Reserved_cost: 0.000106
    Windows_SQL_Web_On_Demand_cost: 0.478
    Windows_SQL_Web_Reserved_cost: 0.396
    Windows_SQL_Std_On_Demand_cost: 0.89
    Windows_SQL_Std_Reserved_cost: 0.808
    Windows_SQL_Ent_On_Demand_cost: 1.91
    Windows_SQL_Ent_Reserved_cost: 1.828
    Linux_SQL_Web_On_Demand_cost: 0.294
    Linux_SQL_Web_Reserved_cost: 0.212
    Linux_SQL_Std_On_Demand_cost: 0.706
    Linux_SQL_Std_Reserved_cost: 0.624
    Linux_SQL_Ent_On_Demand_cost: 1.726
    Linux_SQL_Ent_Reserved_cost: 1.644
    EBS_Optimized_surcharge: 0
    EMR_cost: 0.057
    Name: M5
