apiVersion: perfd/v1
kind: trialConfig
metadata:
  name: instanceType_suite_1 # was .._nginx
  appName: nginx
  appVersion: 1.10.3
  resultBucket: perfd
  logBucket: perfd-log
  autoscale: True
  clusterdown: True
  verbosity: 1
spec:
  instanceGroup:
    - image: 238764668013/perfd-generic
      tenancy: dedicated
      instanceType: c5.xlarge
      numInstance: 5
    - instanceType: r5.xlarge
      numInstance: 5
    - instanceType: m5.xlarge
      numInstance: 5
    - instanceType: c5.2xlarge
      numInstance: 5
    - instanceType: r5.2xlarge
      numInstance: 5
    - instanceType: m5.2xlarge
      numInstance: 5
  metaConfig:
    numRun: 20
  resourceConfig:
    numServerInstance: 1
    numClientInstance: 4
    serverInstanceType: [c5.xlarge, r5.xlarge, m5.xlarge, c5.2xlarge, r5.2xlarge, m5.2xlarge]
    clientInstanceType: c5.xlarge
  appConfig:
    fileSize: 1000
    reqRate: 1000
    numWorkerProc: [4, 4, 4, 8, 8, 8]
    numConn: 50
    duration: 30
    numClientThread: 1
