apiVersion: perfd/v1
kind: trialConfig
metadata:
  name: instanceType_suite_1
  appName: influxdb
  appVersion: 1.7.10
  resultBucket: perfd
  logBucket: perfd-log
  autoscale: True
  clusterdown: True
  verbosity: 1
spec:
  instanceGroup:
    - image: 238764668013/perfd-generic
      tenancy: dedicated
      instanceType: c5.xlarge
      numInstance: 15
    - instanceType: r5.xlarge
      numInstance: 5
    - instanceType: m5.xlarge
      numInstance: 5
    - instanceType: c5.2xlarge
      numInstance: 5
    - instanceType: r5.2xlarge
      numInstance: 5
    - instanceType: m5.2xlarge
      numInstance: 5
  metaConfig:
    numRun: 20
  resourceConfig:
    numServerInstance: 5
    numClientInstance: 4
    serverInstanceType: [c5.xlarge, r5.xlarge, m5.xlarge, c5.2xlarge, r5.2xlarge, m5.2xlarge]
    clientInstanceType: c5.xlarge
  appConfig:
    batchSize: 5000
    numReq: 5
    numPointPerSeries: 100
    fieldPerPoint: 1   # TODO: change the per point size draw from the distribution
    clientConcurrency: 1
    duration: 10
    shardDuration: 7d
    numMeasurement: 1
    tagCard: "10,10,10"
    writeConsistency: "any"
