apiVersion: perfd/v1
kind: trialConfig
metadata:
  name: numPointPerSeries_suite_1_field_vary_new
  appName: influxdb
  appVersion: 1.7.10
  resultBucket: perfd
  logBucket: perfd-log
  autoscale: True
  clusterdown: True
  verbosity: 1
spec:
  instanceGroup:
    - image: 238764668013/perfd-generic
      tenancy: dedicated
      instanceType: c5.xlarge
      numInstance: 9
  metaConfig:
    numRun: 20
  resourceConfig:
    numServerInstance: 5
    numClientInstance: 4
    serverInstanceType: c5.xlarge
    clientInstanceType: c5.xlarge
  appConfig:
    batchSize: 5000
    numReq: 5
    numPointPerSeries: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]
    fieldPerPoint: 1
    clientConcurrency: 1
    duration: 10
    shardDuration: 7d
    numMeasurement: 1
    tagCard: "10,10,10"
    writeConsistency: "any"
    randomField: True
